default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0.0

  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0.0

  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0.0

  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0.0

  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0.0

  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 0.0

  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.0

  robotiq_85_right_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.0